version: '3.7'

networks:
  car-api:

services:
  database:
    ports:
      - "5432:5432"
    networks:
      - car-api
    image: postgres:11
    environment:
      - POSTGRES_USER=car_api_admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cars
    volumes:
      - ./var/lib/postgresql/data

  backend:
    ports:
      - 5000:5000
    networks:
      - car-api
    depends_on:
      - database
    restart: on-failure
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: npm run start:prod
    environment:
      - NODE_ENV=production
      - NODE_PORT=5000
      - DB_TYPE=postgres
      - DB_HOST=database
      - DB_NAME=cars
      - DB_PORT=5432
      - DB_USER=car_api_admin
      - DB_PASSWORD=admin
